### PR TITLE
feat: added example for Crystal language

### PR DESCRIPTION
**Pull request by anton7c3**
This change is [Reviewable](https://reviewable.io/reviews/ycm-core/lsp-examples/26)

### CODE REVIEW

**Comment by bstaletic** [comment]
Thanks for the pull request!

We usually add an install script that would, in this case, install crystalline somewhere in `lsp-examples/crystal/`. Would that be feasible?

**Comment by anton7c3** [comment]
> Thanks for the pull request!
> 
> We usually add an install script that would, in this case, install crystalline somewhere in `lsp-examples/crystal/`. Would that be feasible?

Sure, I think it's possible.
EDIT: done.

**Review by bstaletic — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ycm-core/lsp-examples/26)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @anton7c3)

___
*[crystal/install.py, line 86 at r2](https://reviewable.io/reviews/ycm-core/lsp-examples/26#-MbpyZ4Q91YbBGis99yL:-MbpyZ4Q91YbBGis99yM:b-298d36) ([raw file](https://github.com/ycm-core/lsp-examples/blob/7c62a2648eaf03b15703de27f052c2006db7b97d/crystal/install.py#L86)):*
> ```Python
> 
> try:
>     shutil.move("/tmp/crystalline", "/usr/local/bin/crystalline")
> ```

Let's not write to `/usr`. Let's write it to `lsp-examples/crystal/bin` or something like that, plus a [`snippet.vim`](https://github.com/ycm-core/lsp-examples/blob/master/d/snippet.vim) like the ones that exist for other languages. That would be a correct integration with the top level `install.py`.

And we don't really need the bash script. Windows normally doesn't have a bash shell.

**Comment by anton7c3** [comment]
> > _[Reviewable](https://reviewable.io/reviews/ycm-core/lsp-examples/26)_ status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @anton7c3)
> 
> _[crystal/install.py, line 86 at r2](https://reviewable.io/reviews/ycm-core/lsp-examples/26#-MbpyZ4Q91YbBGis99yL:-MbpyZ4Q91YbBGis99yM:b-298d36) ([raw file](https://github.com/ycm-core/lsp-examples/blob/7c62a2648eaf03b15703de27f052c2006db7b97d/crystal/install.py#L86)):_
> 
> > ```python
> > try:
> >     shutil.move("/tmp/crystalline", "/usr/local/bin/crystalline")
> > ```
> 
> Let's not write to `/usr`. Let's write it to `lsp-examples/crystal/bin` or something like that, plus a [`snippet.vim`](https://github.com/ycm-core/lsp-examples/blob/master/d/snippet.vim) like the ones that exist for other languages. That would be a correct integration with the top level `install.py`.
> 
> And we don't really need the bash script. Windows normally doesn't have a bash shell.

There is a problem with Crystal for Windows. So far it is hardly usable, and no Crystalline version is available at all.
Should I add some kind of stub for windows users?

**Review by bstaletic — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ycm-core/lsp-examples/26)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @anton7c3)

___
*[crystal/install.py, line 86 at r2](https://reviewable.io/reviews/ycm-core/lsp-examples/26#-MbpyZ4Q91YbBGis99yL:-Mc3uzll-0zNQL7GTeLE:b-s1j8pn) ([raw file](https://github.com/ycm-core/lsp-examples/blob/7c62a2648eaf03b15703de27f052c2006db7b97d/crystal/install.py#L86)):*
<details><summary><i>Previously, anton7c3 (Anton) wrote…</i></summary><blockquote>

There is a problem with Crystal for Windows. So far it is hardly usable, and no Crystalline version is available at all.
Should I add some kind of stub for windows users?

</blockquote></details>

```python
if OnWindows():
  sys.exit("Crystalline isn't supported on Windows")
```

Or something like that should be fine.

**Comment by anton7c3** [comment]
> > _[Reviewable](https://reviewable.io/reviews/ycm-core/lsp-examples/26)_ status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @anton7c3)
> 
> _[crystal/install.py, line 86 at r2](https://reviewable.io/reviews/ycm-core/lsp-examples/26#-MbpyZ4Q91YbBGis99yL:-Mc3uzll-0zNQL7GTeLE:b-s1j8pn) ([raw file](https://github.com/ycm-core/lsp-examples/blob/7c62a2648eaf03b15703de27f052c2006db7b97d/crystal/install.py#L86)):_
> Previously, anton7c3 (Anton) wrote…
> 
> ```python
> if OnWindows():
>   sys.exit("Crystalline isn't supported on Windows")
> ```
> 
> Or something like that should be fine.

I've checked python script, it has an error message for all OSes that don't have Crystalline available, Windows included :)
Everything should be fine now.

**Review by bstaletic — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ycm-core/lsp-examples/26)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @anton7c3)

___
*[crystal/install.py, line 86 at r2](https://reviewable.io/reviews/ycm-core/lsp-examples/26#-MbpyZ4Q91YbBGis99yL:-Mc3zMPdCySqM6Ty1MTR:b-78j29c) ([raw file](https://github.com/ycm-core/lsp-examples/blob/7c62a2648eaf03b15703de27f052c2006db7b97d/crystal/install.py#L86)):*
<details><summary><i>Previously, anton7c3 (Anton) wrote…</i></summary><blockquote>

I've checked python script, it has an error message for all OSes that don't have Crystalline available, Windows included :)
Everything should be fine now.

</blockquote></details>

I still think we should install in some local directory and provide a `snippet.vim`, so the users can programatically just source all the snippets for languages they want.

With all other servers in this repo, something like this is possible:

```viml
let lsp_root = '/path/to/lsp-examples'
let enabled_languages = [ ... ]
for lang in enabled_languages
    execute 'source ' . lsp_root . lang . 'snippet.vim
endfor
```

And that's what I'd like to see allowed for crystalline too.

**Review by bstaletic — APPROVED** [review]
Generally, :lgtm: . Squashing commits would be a nice touch, but isn't necessary.

> Reviewed 1 of 2 files at r1, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/lsp-examples/26#-:-Mc4-jt8CVLryn6Atw9F:b-xdxqdx)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @anton7c3)

___
*[crystal/install.py, line 86 at r2](https://reviewable.io/reviews/ycm-core/lsp-examples/26#-MbpyZ4Q91YbBGis99yL:-Mc4-PgtCvjoa0wezypV:blxmsv5) ([raw file](https://github.com/ycm-core/lsp-examples/blob/7c62a2648eaf03b15703de27f052c2006db7b97d/crystal/install.py#L86)):*
<details><summary><i>Previously, bstaletic (Boris Staletic) wrote…</i></summary><blockquote>

I still think we should install in some local directory and provide a `snippet.vim`, so the users can programatically just source all the snippets for languages they want.

With all other servers in this repo, something like this is possible:

```viml
let lsp_root = '/path/to/lsp-examples'
let enabled_languages = [ ... ]
for lang in enabled_languages
    execute 'source ' . lsp_root . lang . 'snippet.vim
endfor
```

And that's what I'd like to see allowed for crystalline too.
</blockquote></details>

Retracting the last comment! I completely missed that you pushed another commit!

**Comment by anton7c3** [comment]
Is there anything else I have missed?

**Comment by bstaletic** [comment]
I've tested the install script on my machine. Seems to be working. Merging.

**Comment by bstaletic** [comment]
@anton7c3 Once again, thanks for the pull request!

**Pull request merged**
