### PR TITLE
Add cmake lsp server

### PR DESCRIPTION
**Pull request by Borwe**
using pip to install cmake language server in a venv dir.

---
This change is [Reviewable](https://reviewable.io/reviews/ycm-core/lsp-examples/23)

### CODE REVIEW

**Review by bstaletic — CHANGES_REQUESTED** [review]
Thanks for the PR!

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/lsp-examples/23#-:-MY_FBYv7vkLqWovC-qA:b-ek0rh5)* status: all files reviewed, 5 unresolved discussions (waiting on @Borwe)

___
*[cmake/install.py, line 1 at r1](https://reviewable.io/reviews/ycm-core/lsp-examples/23#-MY_Hx6v2V4kF9fOC8nG:-MY_Hx6v2V4kF9fOC8nH:b-e48rkh) ([raw file](https://github.com/ycm-core/lsp-examples/blob/b29332316b34313704cf7b3a1fc4cbb90fb3e4d4/cmake/install.py#L1)):*
> ```Python
> #!/usr/bin/env python3
> ```

The style of this script doesn't match others. We generally use snake case for local variables, spaces inside parens and brackets, around operators and after commas.
___
*[cmake/install.py, line 11 at r1](https://reviewable.io/reviews/ycm-core/lsp-examples/23#-MY_GNhM0xP-Emw8gLuB:-MY_GNhM0xP-Emw8gLuC:bpqxwut) ([raw file](https://github.com/ycm-core/lsp-examples/blob/b29332316b34313704cf7b3a1fc4cbb90fb3e4d4/cmake/install.py#L11)):*
> ```Python
> 
> 
> def ProcessRun(args):
> ```

Other scripts don't check if `subprocess.check_call()` finished successfully. If `check_call()` fails, the unhandled exception terminates the script.
___
*[cmake/install.py, line 21 at r1](https://reviewable.io/reviews/ycm-core/lsp-examples/23#-MY_Fk-fClnKkCkB7Mjc:-MY_Fk-fClnKkCkB7Mjd:b4lqypy) ([raw file](https://github.com/ycm-core/lsp-examples/blob/b29332316b34313704cf7b3a1fc4cbb90fb3e4d4/cmake/install.py#L21)):*
> ```Python
> 
> 
> def CheckIfHavePipInstalled():
> ```

For this, ycmd's `utils.py` has `PathToFirstExistingExecutable()`. Or you can call `FindExecutable()` once and then `FindExecutableOrDie()` the second time.

Just copy the already existing utilities.
___
*[cmake/install.py, line 57 at r1](https://reviewable.io/reviews/ycm-core/lsp-examples/23#-MY_HKev2VHh5CtMvhPU:-MY_HKev2VHh5CtMvhPV:b2651za) ([raw file](https://github.com/ycm-core/lsp-examples/blob/b29332316b34313704cf7b3a1fc4cbb90fb3e4d4/cmake/install.py#L57)):*
> ```Python
> def Main():
>     pipToUse=CheckIfHavePipInstalled()
>     if pipToUse==None:
> ```

Usually you would check this with `is`.
___
*[cmake/install.py, line 59 at r1](https://reviewable.io/reviews/ycm-core/lsp-examples/23#-MY_H8ir7siVjEVzpO1C:-MY_H8ir7siVjEVzpO1D:b-tk71jp) ([raw file](https://github.com/ycm-core/lsp-examples/blob/b29332316b34313704cf7b3a1fc4cbb90fb3e4d4/cmake/install.py#L59)):*
> ```Python
>     if pipToUse==None:
>         print("Couldn't find pip in your system, please put it on path")
>         return
> ```

Instead of `print(message)`/`return`, you can just use `sys.exit(message)`.

**Review by Borwe — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ycm-core/lsp-examples/23)* status: 2 of 3 files reviewed, 5 unresolved discussions (waiting on @Borwe and @bstaletic)

___
*[cmake/install.py, line 59 at r1](https://reviewable.io/reviews/ycm-core/lsp-examples/23#-MY_H8ir7siVjEVzpO1C:-MYiqyQaA1xxiaTdGJQP:bymb1sk) ([raw file](https://github.com/ycm-core/lsp-examples/blob/b29332316b34313704cf7b3a1fc4cbb90fb3e4d4/cmake/install.py#L59)):*
<details><summary><i>Previously, bstaletic (Boris Staletic) wrote…</i></summary><blockquote>

Instead of `print(message)`/`return`, you can just use `sys.exit(message)`.
</blockquote></details>

I believe the corrections are now done.

**Review by puremourning — CHANGES_REQUESTED** [review]
Thanks for doing this.

So I tried out the server and it seems to be broken.

It's sending `null` for `insertTextFormat` leading to exceptions, at least in my fork:

```
2021-04-20 17:32:21,948 - DEBUG - RX: Received message: b'{"id": 3, "jsonrpc": "2.0", "result": {"isIncomplete": false, "items": [{"label": "set", "kind": 3, "detail": null, "documentation": "```cmake\\nset()\\n```", "deprecated": false, "preselect": false, "sortText": null, "filterText": null, "insertText": "set", "insertTextFormat": null, "textEdit": null, "additionalTextEdits": null, "commitCharacters": null, "command": null, "data": null}, {"label": "set_directory_properties", "kind": 3, "detail": null, "documentation": "```cmake\\nset_directory_properties(PROPERTIES prop1 value1 [prop2 value2] ...)\\n```", "deprecated": false, "preselect": false, "sortText": null, "filterText": null, "insertText": "set_directory_properties", "insertTextFormat": null, "textEdit": null, "additionalTextEdits": null, "commitCharacters": null, "command": null, "data": null}, {"label": "set_property", "kind": 3, "detail": null, "documentation": "```cmake\\nset_property(<GLOBAL                      |\\n              DIRECTORY [<dir>]           |\\n              TARGET    [<target1> ...]   |\\n              SOURCE    [<src1> ...]\\n                        [DIRECTORY <dirs> ...] |\\n                        [TARGET_DIRECTORY <targets> ...]\\n              INSTALL   [<file1> ...]     |\\n              TEST      [<test1> ...]     |\\n              CACHE     [<entry1> ...]    >\\n             [APPEND] [APPEND_STRING]\\n             PROPERTY <name> [<value1> ...])\\n```", "deprecated": false, "preselect": false, "sortText": null, "filterText": null, "insertText": "set_property", "insertTextFormat": null, "textEdit": null, "additionalTextEdits": null, "commitCharacters": null, "command": null, "data": null}, {"label": "set_source_files_properties", "kind": 3, "detail": null, "documentation": "```cmake\\nset_source_files_properties(<files> ...\\n                            [DIRECTORY <dirs> ...]\\n                            [TARGET_DIRECTORY <targets> ...]\\n                            PROPERTIES <prop1> <value1>\\n                            [<prop2> <value2>] ...)\\n```", "deprecated": false, "preselect": false, "sortText": null, "filterText": null, "insertText": "set_source_files_properties", "insertTextFormat": null, "textEdit": null, "additionalTextEdits": null, "commitCharacters": null, "command": null, "data": null}, {"label": "set_target_properties", "kind": 3, "detail": null, "documentation": "```cmake\\nset_target_properties(target1 target2 ...\\n                      PROPERTIES prop1 value1\\n                      prop2 value2 ...)\\n```", "deprecated": false, "preselect": false, "sortText": null, "filterText": null, "insertText": "set_target_properties", "insertTextFormat": null, "textEdit": null, "additionalTextEdits": null, "commitCharacters": null, "command": null, "data": null}, {"label": "set_tests_properties", "kind": 3, "detail": null, "documentation": "```cmake\\nset_tests_properties(test1 [test2...] PROPERTIES prop1 value1 prop2 value2)\\n```", "deprecated": false, "preselect": false, "sortText": null, "filterText": null, "insertText": "set_tests_properties", "insertTextFormat": null, "textEdit": null, "additionalTextEdits": null, "commitCharacters": null, "command": null, "data": null}]}}'
Traceback (most recent call last):
  File "/Users/ben/.vim/bundle/YouCompleteMe/third_party/ycmd/third_party/bottle/bottle.py", line 868, in _handle
    return route.call(**args)
  File "/Users/ben/.vim/bundle/YouCompleteMe/third_party/ycmd/third_party/bottle/bottle.py", line 1748, in wrapper
    rv = callback(*a, **ka)
  File "/Users/ben/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/watchdog_plugin.py", line 97, in wrapper
    return callback( *args, **kwargs )
  File "/Users/ben/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/hmac_plugin.py", line 62, in wrapper
    body = callback( *args, **kwargs )
  File "/Users/ben/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/handlers.py", line 119, in GetCompletions
    completions = filetype_completer.ComputeCandidates( request_data )
  File "/Users/ben/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/completers/completer.py", line 304, in ComputeCandidates
    candidates = self._GetCandidatesFromSubclass( request_data )
  File "/Users/ben/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/completers/language_server/language_server_completer.py", line 1323, in _GetCandidatesFromSubclass
    raw_completions, is_incomplete = self.ComputeCandidatesInner( request_data,
  File "/Users/ben/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/completers/language_server/language_server_completer.py", line 1308, in ComputeCandidatesInner
    return ( self._CandidatesFromCompletionItems(
  File "/Users/ben/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/completers/language_server/language_server_completer.py", line 1445, in _CandidatesFromCompletionItems
    _InsertionTextForItem( request_data, item ) )
  File "/Users/ben/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/completers/language_server/language_server_completer.py", line 2879, in _InsertionTextForItem
    if lsp.INSERT_TEXT_FORMAT[ item.get( 'insertTextFormat', 1 ) ] == 'Snippet':
```

This is completely invalid LSP. Raised https://github.com/regen100/cmake-language-server/issues/39.

> Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/lsp-examples/23#-:-MYk2lhU-l5CG8miUzwZ:b-rwla79)* status: all files reviewed, 18 unresolved discussions (waiting on @Borwe and @bstaletic)

*[a discussion](https://reviewable.io/reviews/ycm-core/lsp-examples/23#-MYk7Q_qA4M2TxwH6wG2:-MYk7Q_qA4M2TxwH6wG3:b-r3ybmg) (no related file):*
The README.md needs updating.

---
___
*[.gitignore, line 10 at r2](https://reviewable.io/reviews/ycm-core/lsp-examples/23#-MYk1EJ-2a-dgKgaeiV0:-MYk1EJ-2a-dgKgaeiV1:b-z7o3pw) ([raw file](https://github.com/ycm-core/lsp-examples/blob/3c4686aa55435b5cd07cf642961c4b969abdd482/.gitignore#L10)):*
> ```ignore
> node_modules/
> vimrc.generated
> venv/
> ```

do this in a .gitignore inside the `cmake` directory? 
___
*[cmake/install.py, line 2 at r2](https://reviewable.io/reviews/ycm-core/lsp-examples/23#-MYk2tC2AizeLuV5q1H5:-MYk2tC2AizeLuV5q1H6:bi7rw6h) ([raw file](https://github.com/ycm-core/lsp-examples/blob/3c4686aa55435b5cd07cf642961c4b969abdd482/cmake/install.py#L2)):*
> ```Python
> #!/usr/bin/env python3
> import subprocess, platform, sys, os
> ```

one import per `import` statement
___
*[cmake/install.py, line 11 at r2](https://reviewable.io/reviews/ycm-core/lsp-examples/23#-MYk1Ok04O16B-HId6UR:-MYk1Ok04O16B-HId6US:bjqqwym) ([raw file](https://github.com/ycm-core/lsp-examples/blob/3c4686aa55435b5cd07cf642961c4b969abdd482/cmake/install.py#L11)):*
> ```Python
> 
> 
> def ProcessRun( args ):
> ```

Should be `RunProcess` but I really don't see the point in the wrapper as it just calls `subprocess.check_call()`
___
*[cmake/install.py, line 15 at r2](https://reviewable.io/reviews/ycm-core/lsp-examples/23#-MYk0lvH0KU7GFxXD2sq:-MYk0lvH0KU7GFxXD2sr:b92x6qa) ([raw file](https://github.com/ycm-core/lsp-examples/blob/3c4686aa55435b5cd07cf642961c4b969abdd482/cmake/install.py#L15)):*
> ```Python
> 
> 
> def isPipInstalled():
> ```

IsPipInstalled
___
*[cmake/install.py, line 22 at r2](https://reviewable.io/reviews/ycm-core/lsp-examples/23#-MYk0pIJ18SItC-2pqYW:-MYk0pIJ18SItC-2pqYX:bie7agh) ([raw file](https://github.com/ycm-core/lsp-examples/blob/3c4686aa55435b5cd07cf642961c4b969abdd482/cmake/install.py#L22)):*
> ```Python
>         return "pip"
>     except:
>         cmd=[ "pip3" , "--version" ]
> ```

try pip3 first, as pip might be python2 on many systems.

However, I think the correct way to check for pip would be `[ sys.executable, '-m', 'pip' ]`

In the event that it's not found, we can recommend users run `sys.executable + '-m ensurepip'` ?
___
*[cmake/install.py, line 42 at r2](https://reviewable.io/reviews/ycm-core/lsp-examples/23#-MYk2yzO1XeE9kvY7V23:-MYk2yzO1XeE9kvY7V24:bqwrpw6) ([raw file](https://github.com/ycm-core/lsp-examples/blob/3c4686aa55435b5cd07cf642961c4b969abdd482/cmake/install.py#L42)):*
> ```Python
>     bin_dir = "bin"
>     if OnWindows():
>         bin_dir = "Scripts"
> ```

2 space indent (please apply everywhere)
___
*[cmake/install.py, line 44 at r2](https://reviewable.io/reviews/ycm-core/lsp-examples/23#-MYk30ww7mQiraa7E0mF:-MYk30ww7mQiraa7E0mG:b-k7l109) ([raw file](https://github.com/ycm-core/lsp-examples/blob/3c4686aa55435b5cd07cf642961c4b969abdd482/cmake/install.py#L44)):*
> ```Python
>         bin_dir = "Scripts"
> 
>     pip_cmd = os.path.join( DIR_OF_THIS_SCRIPT , "venv" , bin_dir , "pip" )
> ```

no space before `,`
___
*[cmake/install.py, line 45 at r2](https://reviewable.io/reviews/ycm-core/lsp-examples/23#-MYk34cz9PPzeqk_2yIG:-MYk34cz9PPzeqk_2yIH:b-ak3vb6) ([raw file](https://github.com/ycm-core/lsp-examples/blob/3c4686aa55435b5cd07cf642961c4b969abdd482/cmake/install.py#L45)):*
> ```Python
> 
>     pip_cmd = os.path.join( DIR_OF_THIS_SCRIPT , "venv" , bin_dir , "pip" )
>     cmd=[ pip_cmd , "install" , "cmake-language-server" ]
> ```

spaces around `=`
___
*[cmake/install.py, line 54 at r2](https://reviewable.io/reviews/ycm-core/lsp-examples/23#-MYk1_bB95Jl4IaV8W-v:-MYk1_bB95Jl4IaV8W-w:bauu2vz) ([raw file](https://github.com/ycm-core/lsp-examples/blob/3c4686aa55435b5cd07cf642961c4b969abdd482/cmake/install.py#L54)):*
> ```Python
> 
> def Main():
>     pip_to_use = isPipInstalled()
> ```

I don't really understand this. We're using a virtual env, then using pip from within the virtualenv... doens't running `python -m venv` ensure that pip is installed in the vent?

We don't ever actually use `pip_to_use`
___
*[cmake/install.py, line 58 at r2](https://reviewable.io/reviews/ycm-core/lsp-examples/23#-MYk1ocd034DZqdVxwtH:-MYk1ocd034DZqdVxwtI:bhz3gto) ([raw file](https://github.com/ycm-core/lsp-examples/blob/3c4686aa55435b5cd07cf642961c4b969abdd482/cmake/install.py#L58)):*
> ```Python
>         sys.exit( "Couldn't find pip in your system, please put it on path" )
> 
>     created_venv = CreateVenvDir()
> ```

`if not CreateVenvDir():`
___
*[cmake/install.py, line 62 at r2](https://reviewable.io/reviews/ycm-core/lsp-examples/23#-MYk1sHF9J6Q4wMbVrOq:-MYk1sHF9J6Q4wMbVrOr:b-afjswj) ([raw file](https://github.com/ycm-core/lsp-examples/blob/3c4686aa55435b5cd07cf642961c4b969abdd482/cmake/install.py#L62)):*
> ```Python
>         sys.exit( "Error, couldn't create the venv directory to be used" )
> 
>     install_cmake = InstallCMakeLanguageServer()
> ```

`if not InstallCMakeLanguageServer():`
___
*[cmake/snippet.vim, line 2 at r2](https://reviewable.io/reviews/ycm-core/lsp-examples/23#-MYk2Mia4YqfD8Wrpjqu:-MYk2Mia4YqfD8Wrpjqv:b-tfzqoq) ([raw file](https://github.com/ycm-core/lsp-examples/blob/3c4686aa55435b5cd07cf642961c4b969abdd482/cmake/snippet.vim#L2)):*
this is a tautology. win32 is true in all cases where win64 is true:

> win32			Win32 version of Vim (MS-Windows 95 and later, 32 or
			64 bits)
win32unix		Win32 version of Vim, using Unix files (Cygwin)
win64			Win64 version of Vim (MS-Windows 64 bit).

I think you can just check `has( 'win32' )`

**Review by Borwe — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ycm-core/lsp-examples/23)* status: 0 of 4 files reviewed, 18 unresolved discussions (waiting on @Borwe, @bstaletic, and @puremourning)

___
*[cmake/snippet.vim, line 2 at r2](https://reviewable.io/reviews/ycm-core/lsp-examples/23#-MYk2Mia4YqfD8Wrpjqu:-MZ7wHOa9k-1o0ETrQA2:b-kndl1s) ([raw file](https://github.com/ycm-core/lsp-examples/blob/3c4686aa55435b5cd07cf642961c4b969abdd482/cmake/snippet.vim#L2)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

this is a tautology. win32 is true in all cases where win64 is true:

> win32			Win32 version of Vim (MS-Windows 95 and later, 32 or
			64 bits)
win32unix		Win32 version of Vim, using Unix files (Cygwin)
win64			Win64 version of Vim (MS-Windows 64 bit).

I think you can just check `has( 'win32' )`

</blockquote></details>

Did some more fixes.

**Review by puremourning — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/lsp-examples/23)* status: 4 of 5 files reviewed, 7 unresolved discussions (waiting on @Borwe and @bstaletic)

*[a discussion](https://reviewable.io/reviews/ycm-core/lsp-examples/23#-MYk7Q_qA4M2TxwH6wG2:-MZ7xZbS3_zFMc8OBblH:b-nk9xxt) (no related file):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

The README.md needs updating.
</blockquote></details>

This still needs doing.

---
___
*[cmake/install.py, line 11 at r1](https://reviewable.io/reviews/ycm-core/lsp-examples/23#-MY_GNhM0xP-Emw8gLuB:-MZ7wyxF-SRD4H9SmDAh:b-1qq5r9) ([raw file](https://github.com/ycm-core/lsp-examples/blob/b29332316b34313704cf7b3a1fc4cbb90fb3e4d4/cmake/install.py#L11)):*
<details><summary><i>Previously, bstaletic (Boris Staletic) wrote…</i></summary><blockquote>

Other scripts don't check if `subprocess.check_call()` finished successfully. If `check_call()` fails, the unhandled exception terminates the script.
</blockquote></details>

Agree with Boris. This approach suppresses the _actual_ exception, which makes debugging harder.
___
*[cmake/install.py, line 34 at r3](https://reviewable.io/reviews/ycm-core/lsp-examples/23#-MZ7xGMvBjYED2fMaar7:-MZ7xGMw7UT-uDmvSQZU:bcyztqx) ([raw file](https://github.com/ycm-core/lsp-examples/blob/6cfd916abec96d4d8b689b4ee4dc466f8b87e33f/cmake/install.py#L34)):*
> ```Python
>     subprocess.check_call( cmd )
>     return True
>   except:
> ```

Better to not catch the exception, so that we see _what _ the exception is. In general bare exception ( `except:` is an anti pattern)

**Review by puremourning — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/lsp-examples/23)* status: all files reviewed, 6 unresolved discussions (waiting on @Borwe and @bstaletic)

**Review by Borwe — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ycm-core/lsp-examples/23)* status: 4 of 5 files reviewed, 6 unresolved discussions (waiting on @Borwe, @bstaletic, and @puremourning)

___
*[cmake/install.py, line 11 at r1](https://reviewable.io/reviews/ycm-core/lsp-examples/23#-MY_GNhM0xP-Emw8gLuB:-MZNQ9E46JyXGvLQT6Cc:bhfmmqx) ([raw file](https://github.com/ycm-core/lsp-examples/blob/b29332316b34313704cf7b3a1fc4cbb90fb3e4d4/cmake/install.py#L11)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

Agree with Boris. This approach suppresses the _actual_ exception, which makes debugging harder.
</blockquote></details>

Done, removed try catch, but don't know what is expected to be added in the README, everything seems okay, maybe an idea LOL!.

**Review by puremourning — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/lsp-examples/23#-:-MZNRSqE0MI2r7R61dzP:bnfp4nl)* status: all files reviewed, 5 unresolved discussions (waiting on @Borwe and @bstaletic)

**Review by bstaletic — APPROVED** [review]
Thanks for the PR.

> Reviewed 2 of 4 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/lsp-examples/23#-:-MZO8J341bQTujqGl_iz:b-ek0rgs)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Borwe)

**Comment by bstaletic** [comment]
@puremourning We don't have Mergify rules for this repo.

**Pull request merged**
