### PR TITLE
Use python for install scripts

### PR DESCRIPTION
**Pull request by bstaletic**
The only thing I'm unsure about is if I should be using `FindExecutableOrDie()` for `git`.

Is it `git.exe` on Windows?

---
This change is [Reviewable](https://reviewable.io/reviews/ycm-core/lsp-examples/2)

### CODE REVIEW

**Review by puremourning — APPROVED** [review]
Assuming this all works.

**Comment by bstaletic** [comment]
I tested all the scripts on linux... \*shrug\*

**Comment by puremourning** [comment]
Ditto. I see this repo as best efforts/equivalent of wiki. We can reference it from the YCM readme. It would be interesting to have a voting system to ‘promote’ languages to first class support with tests. But meh.

**Comment by bstaletic** [comment]
Open an issue for every language in the list and you have a voting system.

**Pull request merged**
