### PR TITLE
add racket lsp config for ycm

### PR DESCRIPTION
**Pull request by kanitkameh**
Requires racket to be installed and the `raco` command to be present on the system so the lsp can be installed.

- - -
This change is [Reviewable](https://reviewable.io/reviews/ycm-core/lsp-examples/39)

### CODE REVIEW

**Review by bstaletic — CHANGES_REQUESTED** [review]
Thanks for the pull request. I always like seeing new servers just work in this repo.

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/lsp-examples/39#-:-NfqstAOEfIwP7Ck3AcD:bb7w6li)* status: all files reviewed, 2 unresolved discussions (waiting on @kanitkameh)

___
*[`racket/install.py` line 49 at r1](https://reviewable.io/reviews/ycm-core/lsp-examples/39#-Nfqt1c47edmC_B8_HGl:-Nfqt1c47edmC_B8_HGm:b5lb312) ([raw file](https://github.com/ycm-core/lsp-examples/blob/e9b75faffca0b73482e95ca92f16cdf382390987/racket/install.py#L49)):*
> ```Python
> 
> def Main():
>   git = FindExecutableOrDie('raco', 'raco is required to setup Racket language server')
> ```

This looks weird.

Shouldn't that be `raco = FindExecutableOrDie(...)`?
___
*[`racket/install.py` line 54 at r1](https://reviewable.io/reviews/ycm-core/lsp-examples/39#-NfqtV2SAIW1ZIPzM7fh:-NfqtV2SAIW1ZIPzM7fi:b-o7t8id) ([raw file](https://github.com/ycm-core/lsp-examples/blob/e9b75faffca0b73482e95ca92f16cdf382390987/racket/install.py#L54)):*
> ```Python
>   os.system("raco pkg install racket-langserver")
>   # Used by Vim when it recognizes racket filetype 
>   os.system("raco pkg install fmt")
> ```

Instead of `os.system` it would be better to use `subprocess.check_call`.

You can take a look here for "inspiration":
https://github.com/ycm-core/lsp-examples/blob/f745e761a8944a00d70b4dc2aad62d455910ff83/css/install.py#L49

**Comment by kanitkameh** [comment]
The `git` was a mistake because I copied code from other lsp install examples. I changed the code to use `subprocess.check_call` however I catch the exception thrown by it because when the package is already installed it returns 1 as return code.

**Review by bstaletic — CHANGES_REQUESTED** [review]
Another thing I forgot was the README. Could you add a few words to it? Do users need any extra setup? Does the server work well, or are there some quirks?

If it works well and there's no additional setup needed, just add `racket` to the list of languages that work.

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/lsp-examples/39#-:-NfrKWqZCe3XjrFzU4n7:b5n2ioa)* status: all files reviewed, 1 unresolved discussion (waiting on @kanitkameh)

___
*[`racket/install.py` line 53 at r2](https://reviewable.io/reviews/ycm-core/lsp-examples/39#-NfrJOkq8VbnKVmePeaC:-NfrJOkq8VbnKVmePeaD:b-zasoig) ([raw file](https://github.com/ycm-core/lsp-examples/blob/305e230d4bd5a93fe97ed4649e7d8de447971e71/racket/install.py#L53)):*
> ```Python
>   except subprocess.CalledProcessError as calledProcessError:
>     # package is already installed if return code is 1
>     if calledProcessError.returncode != 1:
> ```

Return code `1` usually means "generic error". I have just tried to run this installation script without internet, to make it fail, but we "succeeded":

```
Installing fmt from raco
Resolving "fmt" via https://download.racket-lang.org/releases/8.10/catalog/
tcp-connect: host not found
  hostname: download.racket-lang.org
  port number: 443
  system error: Temporary failure in name resolution; gai_err=-3
  context...:
   /usr/share/racket/collects/openssl/mzssl.rkt:1739:0: do-ssl-connect
   /usr/share/racket/collects/racket/contract/private/arrow-val-first.rkt:555:3
   /usr/share/racket/collects/net/http-client.rkt:67:0: http-conn-open!
   /usr/share/racket/collects/net/http-client.rkt:274:0: http-conn-open
   /usr/share/racket/collects/racket/contract/private/arrow-val-first.rkt:555:3
   /usr/share/racket/collects/net/url.rkt:202:0: http://getpost-impure-port
   /usr/share/racket/collects/net/url.rkt:305:0: get-pure-port/headers
   /usr/share/racket/collects/racket/contract/private/arrow-val-first.rkt:555:3
   /usr/share/racket/collects/pkg/private/network.rkt:59:3
   /usr/share/racket/collects/pkg/private/catalog.rkt:218:0: read-from-server
   /usr/share/racket/collects/pkg/private/catalog.rkt:135:2: lookup-normally
   /usr/share/racket/collects/pkg/private/prefetch.rkt:129:4
   /usr/share/racket/collects/pkg/private/prefetch.rkt:128:2
   /usr/share/racket/collects/pkg/private/catalog.rkt:132:0: package-catalog-lookup
   /usr/share/racket/collects/pkg/private/catalog.rkt:200:0: package-catalog-lookup-source
   /usr/share/racket/collects/pkg/private/clone-path.rkt:372:0: desc->repo
   ...
** SUCCEEDED **: racket
OK, now add the following to your vimrc:
```

I would be okay with no trying to be smart and just letting errors propagate, even "already installed" errors.
With `subprocess.Popen()` you could redirect stdout/stderr and parse, but I also do not think parsing plain text is particularly smart.

**Comment by kanitkameh** [comment]
Good news! After reading the `raco` documentation I found that you can ignore already installed packages thus return status code 0. Everything works as expected now. I also updated the `README.md` to include `Racket`.

**Review by bstaletic — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/lsp-examples/39#-:-Nft1ZN45kKJLcP4SiCj:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kanitkameh)

**Comment by bstaletic** [comment]
Thanks for the pull request.

**Pull request merged**
