### PR TITLE
Added angular LSP server, works even with html

### PR DESCRIPTION
**Pull request by Borwe**
Added angular LSP server with angular service from angular.io, seems to work.
Checked even working on html stuff.

---
This change is [Reviewable](https://reviewable.io/reviews/ycm-core/lsp-examples/12)

### CODE REVIEW

**Review by bstaletic — CHANGES_REQUESTED** [review]
Thanks for the pull request. Just clean up the whitespace and we can merge this.

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/lsp-examples/12#-:-M8FB55g4wQvS_5uaOUF:b-rusefp)* status: all files reviewed, 1 unresolved discussion (waiting on @Borwe)

___
*[README.md, line 54 at r1](https://reviewable.io/reviews/ycm-core/lsp-examples/12#-M8FAq6o5StZOdvqZ6SZ:-M8FAq6o5StZOdvqZ6S_:bu8itk3) ([raw file](https://github.com/ycm-core/lsp-examples/blob/36b3846f6c4b3e6a8d266d792aeb7f78cb092eff/README.md#L54)):*
> ```Markdown
>   \     expand( s:lsp . '/angular/node_modules/' ),                           
>   \     '--stdio' ],                                                          
>   \ 	'filetypes': [ 'ts','html' ],                                             
> ```

There's some odd whitespace here. There are tabs and trailing spaces.

**Review by bstaletic — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/lsp-examples/12)* status: all files reviewed, 1 unresolved discussion (waiting on @Borwe)

___
*[README.md, line 54 at r1](https://reviewable.io/reviews/ycm-core/lsp-examples/12#-M8FAq6o5StZOdvqZ6SZ:-M8FFEuP3Yx3yIAEldLp:b-ww6akc) ([raw file](https://github.com/ycm-core/lsp-examples/blob/36b3846f6c4b3e6a8d266d792aeb7f78cb092eff/README.md#L54)):*
<details><summary><i>Previously, bstaletic (Boris Staletic) wrote…</i></summary><blockquote>

There's some odd whitespace here. There are tabs and trailing spaces.
</blockquote></details>

So the tabs got fixed, but the trailing spaces are still there.

You can execute `%s/\s\+$//`.

**Review by puremourning — CHANGES_REQUESTED** [review]
Wow, thanks for the solid contribution!

> *[Reviewable](https://reviewable.io/reviews/ycm-core/lsp-examples/12#-:-M8FFsgp0yFfa8HbPHdv:b-qz9cmr)* status: all files reviewed, 4 unresolved discussions (waiting on @Borwe)

___
*[README.md, line 54 at r1](https://reviewable.io/reviews/ycm-core/lsp-examples/12#-M8FEPCb6vuvbAKbskB4:-M8FEPCc0Oa15I8L2ACf:b-8jxgxd) ([raw file](https://github.com/ycm-core/lsp-examples/blob/36b3846f6c4b3e6a8d266d792aeb7f78cb092eff/README.md#L54)):*
> ```Markdown
>   \     expand( s:lsp . '/angular/node_modules/' ),                           
>   \     '--stdio' ],                                                          
>   \ 	'filetypes': [ 'ts','html' ],                                             
> ```

should this include `javascriptreact` and `tyspescriptreact` ? I don't know all these wonky frameworks, but is angular somehow related to react? Or are they different ?

Also, we should probably _not_ include `ts` here, right ? that would probably not work if the user has the `--ts-completer` (`tsserver`) anyway, right ?
___
*[angular/install.py, line 48 at r1](https://reviewable.io/reviews/ycm-core/lsp-examples/12#-M8FFYFgEzIgvKxd2xik:-M8FFYFgEzIgvKxd2xil:b-lpwlec) ([raw file](https://github.com/ycm-core/lsp-examples/blob/36b3846f6c4b3e6a8d266d792aeb7f78cb092eff/angular/install.py#L48)):*
> ```Python
> 
> def Main():
>   npm = FindExecutableOrDie( 'npm', 'npm is required to set up Tern.' )
> ```

`Tern` -> `angular language server`
___
*[angular/package.json, line 2 at r1](https://reviewable.io/reviews/ycm-core/lsp-examples/12#-M8FFp6zEoNfWUfVLP6D:-M8FFp6zEoNfWUfVLP6E:b-hxiuut) ([raw file](https://github.com/ycm-core/lsp-examples/blob/36b3846f6c4b3e6a8d266d792aeb7f78cb092eff/angular/package.json#L2)):*
> ```JSON
> {
>   "description": "ycmd yaml-language-server runtime area",
> ```

yaml ?

**Review by bstaletic — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ycm-core/lsp-examples/12)* status: all files reviewed, 4 unresolved discussions (waiting on @Borwe and @puremourning)

___
*[README.md, line 54 at r1](https://reviewable.io/reviews/ycm-core/lsp-examples/12#-M8FEPCb6vuvbAKbskB4:-M8FGo2s5b8BgV2bKCVR:bafs6v0) ([raw file](https://github.com/ycm-core/lsp-examples/blob/36b3846f6c4b3e6a8d266d792aeb7f78cb092eff/README.md#L54)):*
> Also, we should probably not include ts here, right ? that would probably not work if the user has the --ts-completer (tsserver) anyway, right ?

We can make a note about it, just like the RA/RLS.
___
*[angular/install.py, line 48 at r1](https://reviewable.io/reviews/ycm-core/lsp-examples/12#-M8FFYFgEzIgvKxd2xik:-M8FGz5T1qqFhFE-MpJx:bykozwl) ([raw file](https://github.com/ycm-core/lsp-examples/blob/36b3846f6c4b3e6a8d266d792aeb7f78cb092eff/angular/install.py#L48)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

`Tern` -> `angular language server`
</blockquote></details>

There may be more typos of that sort.

**Review by puremourning — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/lsp-examples/12)* status: all files reviewed, 5 unresolved discussions (waiting on @Borwe and @puremourning)

___
*[README.md, line 48 at r2](https://reviewable.io/reviews/ycm-core/lsp-examples/12#-M8FG0Et9gl1yvlh1-Tx:-M8FG0Et9gl1yvlh1-Ty:b-ha8xim) ([raw file](https://github.com/ycm-core/lsp-examples/blob/14861bd5cd766732fd6503357a3d6d17bb3aee8a/README.md#L48)):*
> ```Markdown
>   \     'name': 'angular',
>   \     'cmdline': [ 'node' ,                                                 
>   \     expand( s:lsp . '/angular/node_modules/@angular/language-server' ),   
> ```

this still looks messed up. it should match the style of all of the others. if you want to break the list entries do it like this:

```viml
\ 'cmdline': [
\   'arg',
\   'arg2......',
\   'arg3 ....'
\  ],
```

**Review by puremourning — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ycm-core/lsp-examples/12)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @Borwe, @bstaletic, and @puremourning)

___
*[README.md, line 48 at r2](https://reviewable.io/reviews/ycm-core/lsp-examples/12#-M8FG0Et9gl1yvlh1-Tx:-M8FfHwC4c9m5bC9FwSZ:bz52jsh) ([raw file](https://github.com/ycm-core/lsp-examples/blob/14861bd5cd766732fd6503357a3d6d17bb3aee8a/README.md#L48)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

this still looks messed up. it should match the style of all of the others. if you want to break the list entries do it like this:

```viml
\ 'cmdline': [
\   'arg',
\   'arg2......',
\   'arg3 ....'
\  ],
```

</blockquote></details>

close enough.

**Review by puremourning — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ycm-core/lsp-examples/12)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @Borwe, @bstaletic, and @puremourning)

**Review by puremourning — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/lsp-examples/12)* status: all files reviewed, 2 unresolved discussions (waiting on @Borwe and @puremourning)

**Review by bstaletic — APPROVED** [review]
I'm fine with this, but there's one unresolved discussion.

@borwe Please open any of the Reviewable links and answer Ben's questions.

> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/lsp-examples/12#-:-M8FgvqsAsXp7772xdvk:b-ayji3j)* status: all files reviewed, 1 unresolved discussion (waiting on @puremourning)

**Review by puremourning — COMMENTED** [review]
meh let's merge this. we can update if needs.

:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/ycm-core/lsp-examples/12#-:-M8Gy5UX7DrcgQYcZO3u:b-6na2cl)* status: all files reviewed, 1 unresolved discussion (waiting on @puremourning)

**Review by puremourning — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/ycm-core/lsp-examples/12)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
