### PR TITLE
Generate the vimrc for users to just source

### PR DESCRIPTION
**Pull request by puremourning**
We have lots of these things now, and managing the vimrc is a bit fiddly (mine is getting big).

Occurred to me that it's super easy to make a file which user can just source based on which ones they chose.

thoughts ?

Other changes:

* made some install.py files executable
* made one of them work with pip3 rather than pip
* fixed purescript/viml error

---
This change is [Reviewable](https://reviewable.io/reviews/ycm-core/lsp-examples/17)

### CODE REVIEW

**Comment by bstaletic** [comment]
I really like the idea, but I don't have the time to review right now. My `.vim/plugin/Ycm.vim` is getting filled with `ycm_language_server` setup.

**Comment by puremourning** [comment]
Sure no rush.

**Review by bstaletic — APPROVED** [review]
:lgtm: with one non-blocking comment.

> Reviewed 29 of 29 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/lsp-examples/17#-:-MFB2OUl5VWLZsMH0DvO:b-z1kfcb)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[install.py, line 73 at r1](https://reviewable.io/reviews/ycm-core/lsp-examples/17#-MFB1XSN0hP_0IjlfjOz:-MFB1XSN0hP_0IjlfjP-:b-7275hk) ([raw file](https://github.com/ycm-core/lsp-examples/blob/41fae22e636e288a6f88c97a939e7a615a7e9e65/install.py#L73)):*
> ```Python
>     if os.path.exists( snippet ):
>       with open( snippet, 'r' ) as f:
>         vimrc += f.read()
> ```

This might be faster with a `StringIO` object, due to `str` being immutable. I'm pretty sure I don't care about performance in this case.

**Comment by puremourning** [comment]
Thanks. I should update the README too.

**Comment by puremourning** [comment]
updated README let's merge

**Review by bstaletic — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/lsp-examples/17#-:-MGyGhZqCH07b30SZfqQ:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @puremourning)

___
*[README.md, line 71 at r2](https://reviewable.io/reviews/ycm-core/lsp-examples/17#-MGyG-nj9XrobDtTY70h:-MGyG-nj9XrobDtTY70i:bmv7pgy) ([raw file](https://github.com/ycm-core/lsp-examples/blob/96cdbf594458a452b9f8e6bc59945178f711181d/README.md#L71)):*
> ```Markdown
> * 'project_root_files' (list, optional): List of filename to search for when
>   trying to determine the 'root' of the project. THis is useful for languages or
>   language servers which don't automatically detect the 'workspace' root.
> ```

Should we add `config_sections` (in extra conf) and `capabilities` here? Or do you want me to do it in a separate PR?
___
*[README.md, line 84 at r2](https://reviewable.io/reviews/ycm-core/lsp-examples/17#-MGyGU8T77--5-uZVjNw:-MGyGU8U6eMtEiOcqmJj:b-mbhu6p) ([raw file](https://github.com/ycm-core/lsp-examples/blob/96cdbf594458a452b9f8e6bc59945178f711181d/README.md#L84)):*
> ```Markdown
> 
> Ycmd currently doesn't support `showMessageRequest`, so users need to "import
> build" manually.  Unlike purescript, for scala, this can be done in the editor
> ```

Did you manually reformat this block? You know about `v_gq`, right?

**Review by puremourning — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 29 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/lsp-examples/17#-:-MGyK5k71Bt3GuowrUo_:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @bstaletic)

___
*[README.md, line 71 at r2](https://reviewable.io/reviews/ycm-core/lsp-examples/17#-MGyG-nj9XrobDtTY70h:-MGyJyqF8n5icXEgX_-v:blrc8mc) ([raw file](https://github.com/ycm-core/lsp-examples/blob/96cdbf594458a452b9f8e6bc59945178f711181d/README.md#L71)):*
<details><summary><i>Previously, bstaletic (Boris Staletic) wrote…</i></summary><blockquote>

Should we add `config_sections` (in extra conf) and `capabilities` here? Or do you want me to do it in a separate PR?
</blockquote></details>

I think separate update 
___
*[README.md, line 84 at r2](https://reviewable.io/reviews/ycm-core/lsp-examples/17#-MGyGU8T77--5-uZVjNw:-MGyJv1o3TVYzyBWQld5:b-goszj4) ([raw file](https://github.com/ycm-core/lsp-examples/blob/96cdbf594458a452b9f8e6bc59945178f711181d/README.md#L84)):*
<details><summary><i>Previously, bstaletic (Boris Staletic) wrote…</i></summary><blockquote>

Did you manually reformat this block? You know about `v_gq`, right?
</blockquote></details>

I used gqap

**Pull request merged**
