### PR TITLE
add notice of ycm_extra_conf place for kotlin server setup

### PR DESCRIPTION
**Pull request by Jackey-Huo**
PR for issue #5

---
This change is [Reviewable](https://reviewable.io/reviews/ycm-core/lsp-examples/6)

### CODE REVIEW

**Comment by bstaletic** [comment]
Thanks for the PR. The trouble you encountered could, and probably will, happen to someone else who decides to try some other server, depending on how sensitive the server is to correct `rootUri`. For that reason, I think it's better to have this notice in the common part of the README and reference it from the Kotlin section.

Under "Known Issues" there's one mentioning Kotlin, which isn't valid any more. May I ask you to remove it from the README?

**Comment by Jackey-Huo** [comment]
Got it. I have moved the warning into the common part and reference it in kotlin section.

And the expired Known Issue was removed.

**Review by puremourning — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ycm-core/lsp-examples/6)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @Jackey-Huo)

___
*[README.md, line 80 at r2](https://reviewable.io/reviews/ycm-core/lsp-examples/6#-Lluecrc2ZbnUg_3Deq2:-Lluecrc2ZbnUg_3Deq3:b-6oau8m) ([raw file](https://github.com/ycm-core/lsp-examples/blob/50a1d2c3136a0ddee1bf378125cf918958faa4c8/README.md#L80)):*
> ```Markdown
> * Adjust the directory as appropriate
> 
> * **NOTICE**: YCM will regard the path of `.ycm_extra_conf.py` as root path of project folder.
> ```

in YCM docs we prefer to use `**NOTE:**`
___
*[README.md, line 124 at r2](https://reviewable.io/reviews/ycm-core/lsp-examples/6#-Lluevt73VsKMq2Zx4aO:-Lluevt73VsKMq2Zx4aP:bdvetzq) ([raw file](https://github.com/ycm-core/lsp-examples/blob/50a1d2c3136a0ddee1bf378125cf918958faa4c8/README.md#L124)):*
> ```Markdown
> 
> **NOTICE**: As mentioned before, YCM will regard the path of `.ycm_extra_conf.py` as
> root path of kotlin project folder. Miss place the file may cause server crash
> ```

Can we just write:

```markdown
Make sure to either start Vim in the root of the project, or put a `.ycm_extra_conf.py` file in the root of your project, otherwise [the language server may fail](#45).
```

no real need for the rest of the waffle IMO.

**Review by puremourning — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/lsp-examples/6)* status: all files reviewed, 2 unresolved discussions (waiting on @Jackey-Huo)

**Comment by Jackey-Huo** [comment]
I applied the advice. But after a little test, I found open vim in project root doest not work, so have a tiny change in 2nd suggestion.

**Review by puremourning — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ycm-core/lsp-examples/6)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @Jackey-Huo and @puremourning)

___
*[README.md, line 124 at r3](https://reviewable.io/reviews/ycm-core/lsp-examples/6#-LlukzCL8SNojNKwJjhY:-LlukzCL8SNojNKwJjhZ:bxkq88u) ([raw file](https://github.com/ycm-core/lsp-examples/blob/9b20f69a73830cfc28eb28249be915ed507db763/README.md#L124)):*
> ```Markdown
> 
> Make sure to put a `.ycm_extra_conf.py` file in the root of your project, otherwise
> [the language server may fail](#5).
> ```

Ugh, sorry to be a pain, this link doesn't actually work. Can you reinstate your old link (but in this location) ?

Sorry!

**Review by puremourning — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/lsp-examples/6)* status: all files reviewed, 3 unresolved discussions (waiting on @Jackey-Huo)

**Comment by Jackey-Huo** [comment]
link changed

**Review by puremourning — APPROVED** [review]
Thanks! :lgtm: 

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/lsp-examples/6#-:-LlulrkB5O3e63LdQumI:b6duv8n)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
